name: CI/CD Pipeline - Production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow from the GitHub UI

jobs:
  production:
    runs-on: [self-hosted]  # Specify the self-hosted runner with a label 'production'
    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/
    
    - name: Deploy FastAPI Application
      run: |
        # Stop the existing FastAPI process if running
        pkill -f "uvicorn app:app" || echo "No existing process found"
        
        # Start the FastAPI app in the background
        nohup uvicorn app:app --host 0.0.0.0 --port 8000 &

        # Optional: Confirm the app is running
        sleep 5
        curl -I http://127.0.0.1:8000 || echo "FastAPI did not start"
