name: CI/CD Pipeline - FastAPI with Uvicorn

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: self-hosted  # Using your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Stop existing Uvicorn process
      run: |
        pkill -f "uvicorn" || echo "No existing Uvicorn process found"

    - name: Start FastAPI with Uvicorn
      run: |
        cd ~/actions-runner/aiproject/aiproject/aiproject
        nohup /home/subyyal/.local/bin/uvicorn app:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
        sleep 5
        curl -I http://127.0.0.1:8000 || (echo "FastAPI failed to start" && exit 1)

    - name: Display Uvicorn Logs
      run: |
        cat uvicorn.log


      
