name: CI/CD Pipeline - Production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow from the GitHub UI

jobs:
  production:
    runs-on: [self-hosted]  # Specify the self-hosted runner with a label 'production'
    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Path check
      run: |
        pwd
    
    - name: Install dependencies
      run: |
        pwd
        pip install -r requirements.txt
    
    - name: Deploy FastAPI Application
      run: |
          # Start the FastAPI app in the background
            /home/subyyal/actions-runner/aiproject/aiproject/aiproject/startup.sh
            pwd

      
